name: Build and push Docker image
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Docker login
        run: |
          docker login -u "${{ secrets.DOCKER_USERNAME }}" -p "${{ secrets.DOCKER_PASSWORD }}"

      - name: Build image
        run: |
          docker build -t mevipulsingh/flask-app:latest .

      - name: Push image 
        run: |
          docker push mevipulsingh/flask-app:latest
      
      - name: Deploy to EC2
        run: |
          echo "${{ secrets.EC2_SSH_KEY }}" > private_key.pem
          chmod 600 private_key.pem

          ssh -o StrictHostKeyChecking=no \
          -i private_key.pem \
          ubuntu@${{ secrets.EC2_HOST }} << EOF

          docker pull ${{ secrets.DOCKER_USERNAME }}/flask-app:latest

          docker stop flask-app || true

          docker rm flask-app || true

          docker run -d \
            --name flask-app \
            -p 5000:5000 \
            ${{ secrets.DOCKER_USERNAME }}/flask-app:latest

          EOF